apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
  labels:
    app: wordpress
type: Opaque
data:
  password: mysecurepass


---

apiVersion: v1
kind: Secret
metadata:
  name: wordpress
  labels:
    app: wordpress
type: Opaque
data:
  password: mysecurepass
